version: '3'

services:
  db:
    build: ./db/
    ports:
      - "5432:5432"
    env_file:
      - meals.env
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - meals-network

  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - meals.env
    depends_on:
      - db
    networks:
      - meals-network

networks:
  meals-network:
