version: '3'

services:
  database:
    build: ./database/
    env_file: ./meals.env
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - meals-network

  backend:
    build: ./backend/
    env_file: ./meals.env
    depends_on:
      - database
    networks:
      - meals-network

  frontend:
    build: ./frontend/
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - meals-network

networks:
  meals-network:
    driver: bridge